from MPT import MPT

mpt = MPT({})
mpt.update_trie(b'do', b'verb')
mpt.update_trie(b'dog', b'puppy')
mpt.update_trie(b'doge', b'coin')
mpt.update_trie(b'horse', b'stallion')
mpt.update_trie(b'asd', b'qwer')
mpt.update_trie(b'key', b'value')
mpt.update_trie(b'key2', b'value2')
mpt.update_trie(b'key3', b'value3')
mpt.update_trie(b'key4', b'value4')
mpt.update_trie(b'key5', b'value5')
mpt.update_trie(b'key6', b'value6')
mpt.update_trie(b'key7', b'value7')
mpt.update_trie(b'key8', b'value8')
mpt.update_trie(b'key9', b'value9')
mpt.update_trie(b'key10', b'value10')
#print(mpt.root.hex(), mpt.get_node(mpt.root).branches)
#print(mpt.get_node_data(b"horse"))
#print(mpt.root.hex(), mpt.get_node(mpt.root))
#mpt.update_trie(b'horse', b'otro')
#print(mpt.get_node_data(b"key10"))
#print(mpt.root.hex(), mpt.get_node(mpt.root))
mpt.print_mpt(mpt.root)